version: "3.9"
services:
  redis:
    image: redis:latest
    container_name: webhooks-redis
    restart: always
    ports:
      - "127.0.0.1:64269:6379"
    networks:
      intranet:
        ipv4_address: 192.168.240.3

  app:
    image: webhooks-listener
    container_name: webhooks-listener
    restart: always
    build:
      context: ../app
    ports:
      - 64270:443
    depends_on:
      - redis
    networks:
      intranet:
        ipv4_address: 192.168.240.2

networks:
  intranet:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: webhooks-net
      com.docker.network.bridge.enable_icc: "false"
      com.docker.network.enable_ipv6: "false"
    name: "webhooks-listener"
    ipam:
      config:
        - subnet: 192.168.240.0/24
